# Generated by Django 5.1.1 on 2024-09-27 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ARModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('glb_file', models.FileField(upload_to='glb_models/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
